#客户端注册进eureka服务列表
server:
  port: 83

ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 30000
  ReadTimeout: 30000

feign:
  hystrix:
    enabled: ture
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
    register-with-eureka: true #ture 可以让eureka来注册发现
  instance:
    #服务实例名称修改
    instance-id: hystrix
    #访问路径显示IP地址
    prefer-ip-address: true

spring:
  application:
    name: hystrix  #应用名称
  datasource:
    url: jdbc:mysql://47.98.158.112:3306/tx-manager?characterEncoding=UTF-8
    username: hnyskjijobaliyun
    password: 0NUeIgHq47IywCgl@
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool:
      max-active: 600
      max-idle: 300
      max-wait: -1
      min-idle: 0
      timeout: 1000
  aop:
    proxy-target-class: true
# tx-manager 配置  如果是默认的，则不需要填写
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
#  ribbon:
#    loadbalancer:
#      dtx:
#        enabled: true # 是否启动LCN负载均衡策略(优化选项，开启与否，功能不受影响)
  logger:
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

logging:
  level:
    com:
      codingapi:
        txlcn: DEBUG