server:
  port: 7001

spring:
  application:
    name: eureka01 #应用名称

eureka:
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    hostname: localhost
    instance-id: localhost:7001 #指定实例id
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:7002/eureka/
  server:
    enable-self-preservation: false #禁用自我保护模式
    eviction-interval-timer-in-ms: 60000 #清理间隔（单位毫秒，默认是60*1000）