#客户端注册进eureka服务列表
server:
  port: 81
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
    register-with-eureka: true #让eureka注册发现
  instance:
    #服务实例名称修改
    instance-id: ribbon
    #访问路径显示IP地址
    prefer-ip-address: true

spring:
  application:
    name: ribbon  #应用名称